service: cluster-sentence

provider:
  name: aws
  runtime: nodejs8.10

functions:
  clusterSentence:
    handler: cluster-sentence.clusterize
    events:
    - http: POST /cluster-sentence

plugins:
- serverless-offline